import {CountryDetails} from './CountryDetails';
import {Location} from './Location';
import {PlayBook} from './PlayBook';

export interface User {
  id: number;
  name: string;
  email: string;
  email_verified_at: Date;
  created_at: Date;
  updated_at: Date;
  is_active: number;
  tile_image: null;
  hero_image: null;
  logo_image: null;
  mobile_hero_image: null;
  contributor: number;
  is_featured: number;
  about?: string;
  content: null;
  profile_image?: string | null;
  first_name: string;
  last_name: string;
  occupation: string | null;
  home_base: null;
  social_website: string | null;
  social_twitter: string | null;
  social_instagram: string | null;
  social_facebook: string | null;
  social_linkedin: string | null;
  nominated_by: null;
  location_from: null;
  contributor_coordinates: null;
  slug: string | null;
  country_code: string;
  hubspot_id: null;
  marketing_agree: number;
  terms_conditions_agree: number;
  seo_title: null;
  seo_description: null;
  seo_image: null;
  edm_subscribed: number;
  order_date: Date;
  is_onboarded: number;
  is_finished_tutorial: 0 | 1 | '0' | '1';
  tag_cloud: string;
  display_name_single_line: string;
  display_name_line_1: string;
  display_name_line_2: string;
  mobile_profile_image: null;
  photo_credit: null;
  photo_credit_url: null;
  photo_credit_font_colour: null;
  nationality: null;
  country_name: string;
  country_details: CountryDetails;
  nationality_details: CountryDetails;
  full_name: string;
  count_of_playbooks: number;
  count_of_gems: number;
  nominated_by_contributor: any[];
  current_location?: Location;
  playbooks?: PlayBook[];
}
